version : '2'
services :
  php :
    image : php:8.1-fpm
    volumes :
      - ./hijack/ : /var/www/html
      - ./flag/ : /
      - ./sources.list : /etc/apt
      - ./nginx.conf : /etc/nginx/nginx.conf
     ports :
      - "8080:80"
